(1)
SELECT *
FROM T_USER
WHERE OFFICE_CD = '3001'
AND NOT DELET_FLG = '1'
;

(2)
SELECT USER_ID,USER_NM
FROM T_USER
WHERE BIRTHDAY >= '2000'
AND NOT DELET_FLG = '1'
;

(3)
SELECT COUNT(*)
FROM T_USER
WHERE USER_NM LIKE '%田%'
AND NOT DELET_FLG = '1'
;

(4)
SELECT *
FROM T_USER
WHERE NOT DELET_FLG = '1'
ORDER BY BIRTHDAY DESC
;

(5)
SELECT MAX(USER_NM),MIN(USER_NM)
FROM T_USER
WHERE NOT DELET_FLG = '1'
;

(6)
SELECT USER_ID,USER_NM,PASSWORD,OFFICE_CD,COALESCE(BIRTHDAY, '2000-01-01') AS BIRTHDAY,SENIORITY,DELET_FLG
FROM T_USER;
WHERE NOT DELET_FLG = '1'

(7)
SELECT TIMESTAMPDIFF(YEAR,BIRTHDAY,CURDATE())AS age
FROM T_USER
WHERE NOT DELET_FLG = '1'
;
；